mysql:
  host: 0.0.0.0
  port: 3306
  user: urlshort-app
  password: secretpasswordomg
  db: urlshort

postgre:
  user: urlshort_app
  password: secretpasswordomg
  db: urlshort
  host: 0.0.0.0
  port: 5432

redis:
  enabled: true
  host: localhost
  port: 6379
  password: 
  db: 0
  TTL: 60

jwt:
  secret: supersecretjwttoken

server:
  port: 8080